[package]
name = "syosetu2ebook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bpaf = "0.9.12"
regex = "1.10.6"
tempfile = "3.12.0"
ureq = "2.10.1"

