[package]
name = "furigana_gen"
version = "0.1.0"
edition = "2021"

[lib]
name = "furigana_gen"
path = "src/lib.rs"

[dependencies]
vibrato = "0.5"
lz4_flex = "0.11"
regex = "1.10"
once_cell = "1.19"
